services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: runner
    ports:
      - "5000:5000"
    env_file:
      - ./apps/server/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./apps/server/.env:/app/apps/server/.env:ro
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
